In [12]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [13]:
%cd '/content/gdrive/My Drive/Academic Courses/2022-2023/EVEN_SEM/DL/DL-Unit-1'

/content/gdrive/My Drive/Academic Courses/2022-2023/EVEN_SEM/DL/DL-Unit-1


In [14]:
import numpy as np
import pandas as pd

In [15]:
X=pd.read_csv('Iris-new.csv')
X.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [16]:
y=X.Species
y = np.array(y)
x=X.drop('Species',axis=1)
x=x.drop('Id',axis=1)
x=np.array(x)
print(y)
print(x)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 

In [17]:
seedNo = 11
np.random.seed(seedNo) # for reproducibility

"""------------------------------------------------------------------
Type III: Kfold training with k= 5 
---------------------------------------------------------------------"""
 
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import StratifiedKFold # K-fold cross validation - Accuarate but huge computation


# define 5-fold cross validation
kfold = StratifiedKFold(n_splits = 5, shuffle=True, random_state = seedNo)

score_acc = []
score_loss = []
for train, test in kfold.split(x, y):
    # Define model
    mykeras_model = Sequential()
    mykeras_model.add(Dense(10, input_dim = 4, activation = 'relu'))
    mykeras_model.add(Dense(12, activation = 'relu'))
    mykeras_model.add(Dense(1, activation = 'sigmoid'))
    
    
    # Compile model
    mykeras_model.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])
    
    
    # Fit the model - 100 epoch - manual train test
    mykeras_model.fit(x[train], y[train], epochs = 20, batch_size = 8, verbose = 0)
    
    
    # Evaluate model
    perf_meas = mykeras_model.evaluate(x[test], y[test], verbose = 2)    
       
    
#    print("\n")
    print("100 Epoch - 10 fold Results: %s: %f%%" % (mykeras_model.metrics_names[1], perf_meas[1]*100))

##################################  

1/1 - 0s - loss: 0.3863 - accuracy: 0.6667 - 120ms/epoch - 120ms/step
100 Epoch - 10 fold Results: accuracy: 66.666669%
1/1 - 0s - loss: 0.3517 - accuracy: 0.6667 - 110ms/epoch - 110ms/step
100 Epoch - 10 fold Results: accuracy: 66.666669%
1/1 - 0s - loss: 0.3409 - accuracy: 0.6667 - 116ms/epoch - 116ms/step
100 Epoch - 10 fold Results: accuracy: 66.666669%
1/1 - 0s - loss: 0.3485 - accuracy: 0.6667 - 111ms/epoch - 111ms/step
100 Epoch - 10 fold Results: accuracy: 66.666669%
1/1 - 0s - loss: 0.5827 - accuracy: 0.3333 - 120ms/epoch - 120ms/step
100 Epoch - 10 fold Results: accuracy: 33.333334%
