In [ ]:
# Libraries for this section 
import numpy as np
import pandas as pd
import altair as alt
alt.themes.enable('dark')


In [ ]:
x = np.array([[1],
              [2],
              [3]])


In [ ]:
x.shape # (3 dimensions, 1 element on each)

(3, 1)

In [ ]:
print(f'A 3-dimensional vector:\n{x}')


A 3-dimensional vector:
[[1]
 [2]
 [3]]


In [ ]:
#Basic Vector Operations
x = y = np.array([[1],
                  [2],
                  [3]])


In [ ]:
x + y


array([[2],
       [4],
       [6]])

In [ ]:
np.add(x,y)


array([[2],
       [4],
       [6]])

In [ ]:
#Vector Scalar Multiplications
alpha = 2
x = np.array([[1],
             [2],
             [3]])


In [ ]:
alpha * x


array([[2],
       [4],
       [6]])

In [ ]:
#Linear combinations of vectors
a, b = 2, 3
x , y = np.array([[2],[3]]), np.array([[4], [5]])


In [ ]:
a*x + b*y


array([[16],
       [21]])

In [ ]:
#Vector-vector multiplication: dot product
x, y = np.array([[-2],[2]]), np.array([[4],[-3]])


In [ ]:
x.T @ y


array([[-14]])

In [ ]:
#Matrices
# Libraries for this section 
import numpy as np
import pandas as pd
import altair as alt


In [ ]:
A = np.array([[0,2],  # 1st row
              [1,4]]) # 2nd row

print(f'a 2x2 Matrix:\n{A}')


a 2x2 Matrix:
[[0 2]
 [1 4]]


In [ ]:
#Matrix Addition
A = np.array([[0,2],
              [1,4]])
B = np.array([[3,1],
              [-3,2]])
A+B

array([[ 3,  3],
       [-2,  6]])

In [ ]:
#Matrix-scalar multiplication
alpha = 2
A = np.array([[1,2],
              [3,4]])
alpha * A


array([[2, 4],
       [6, 8]])

In [ ]:
np.multiply(alpha, A)


array([[2, 4],
       [6, 8]])

In [ ]:
#Matrix-vector multiplication: dot product
A = np.array([[0,2],
              [1,4]])
x = np.array([[1],
              [2]])
A @ x


array([[4],
       [9]])

In [ ]:
np.dot(A, x)


array([[4],
       [9]])

In [ ]:
#Matrix-matrix multiplication
A = np.array([[0,2],
              [1,4]])
B = np.array([[1,3],
              [2,1]])
A @ B


array([[4, 2],
       [9, 7]])

In [ ]:
#Matrix transpose
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
A.T


array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
from google.colab import files
 
 
uploaded = files.upload()

In [ ]:
import pandas as pd
df = pd.read_csv('"E:/DESKTOP 2023/Assignment_Question/Classification/Heart_disease.csv"')
print(df)